registry: &REGISTRY <set-$REGISTRY-in-environment>
account: &ACCOUNT <set-$REGISTRY-in-environment>
framework: &FRAMEWORK paddlepaddle
version: &VERSION 2.3.0
short_version: &SHORT_VERSION 2.3
repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *REGISTRY, /,  *ACCOUNT, /,
      *REPOSITORY_NAME ]
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *REGISTRY, /,  *ACCOUNT, /,
      *REPOSITORY_NAME ]
images:
  BuildPaddlepaddleGpuPy39Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PADDLEPADDLE_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 10000
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py39
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
                 "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
                         /Dockerfile., *DEVICE_TYPE ]
    # target: sagemaker # 
    enable_test_promotion: true
    # context:
    #   <<: *TRAINING_CONTEXT
  BuildPaddlepaddleCpuPy39TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PADDLEPADDLE_CPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 3700
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py39
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.,
                         *DEVICE_TYPE ]
    # target: sagemaker
    enable_test_promotion: true
    # context:
    #   <<: *TRAINING_CONTEXT
  BuildPaddlepaddleCPUInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PADDLEPADDLE_CPU_INFERENCE_PY3 false
    image_size_baseline: 4899
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py39
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: sagemaker
    enable_test_promotion: true
    # context:
    #   <<: *INFERENCE_CONTEXT
  BuildPaddlepaddleGPUInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PADDLEPADDLE_GPU_INFERENCE_PY3 false
    image_size_baseline: 7738
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py39
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: sagemaker
    enable_test_promotion: true
    # context:
    #   <<: *INFERENCE_CONTEXT
