registry: &REGISTRY <set-$REGISTRY-in-environment>
account: &ACCOUNT <set-$REGISTRY-in-environment>
framework: &FRAMEWORK pytorch
version: &VERSION 1.11.0
short_version: &SHORT_VERSION "1.11"

repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *REGISTRY, /,  *ACCOUNT, /, *REPOSITORY_NAME ]
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *REGISTRY, /, *ACCOUNT, /, *REPOSITORY_NAME ]

images:
  BuildPyTorchCPUPTTrainPy3DockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PYTORCH_CPU_TRAINING_PY3 false
    enable_test_promotion: false
    image_size_baseline: 3600
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: e3
    # context:
    #   <<: *TRAINING_CONTEXT
  BuildPyTorchGPUPTTrainPy3DockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PYTORCH_GPU_TRAINING_PY3 false
    enable_test_promotion: false
    image_size_baseline: 13000
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu113
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: e3
    # context:
    #   <<: *TRAINING_CONTEXT
  BuildPyTorchExampleGPUTrainPy3DockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PYTORCH_GPU_TRAINING_PY3 false
    enable_test_promotion: false
    image_size_baseline: 13000
    base_image_name: BuildPyTorchGPUPTTrainPy3DockerImage
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu113
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-example" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
    # context:
    #   <<: *TRAINING_CONTEXT
  BuildPyTorchCPUPTInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PYTORCH_CPU_INFERENCE_PY3 false
    enable_test_promotion: false
    image_size_baseline: 4899
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: e3
    # context:
    #   <<: *INFERENCE_CONTEXT
  BuildPyTorchGPUPTInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PYTORCH_GPU_INFERENCE_PY3 false
    enable_test_promotion: false
    image_size_baseline: 12500
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu113
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
    # target: e3
    # context:
    #   <<: *INFERENCE_CONTEXT